MONTHLY_QUESTIONS = [
    {"text": "Registration, insurance documents and instruction present in the vehicle?\nРеєстраційні, страхові документи та інструкція присутні в транспортному засобі?", "yes_cell": "D7", "no_cell": "E7", "remark_cell": "F7"},
    {"text": "Keys opening all locks present?\nКлючі присутні в транспортному засобі та відкривають всі замки?", "yes_cell": "D8", "no_cell": "E8", "remark_cell": "F8"},
    {"text": "Engine oil changed as per schedule?\nМоторне масло змінене за графіком?", "yes_cell": "D9", "no_cell": "E9", "remark_cell": "F9"},
    {"text": "Enough oil in the engine?\nДостатня кількість масла в двигуні?", "yes_cell": "D10", "no_cell": "E10", "remark_cell": "F10"},
    {"text": "Enough power steering oil?\nДостатня кількість масла для гідропідсилювача керма?", "yes_cell": "D11", "no_cell": "E11", "remark_cell": "F11"},
    {"text": "Enough liquid in the cooling system?\nДостатньо рідини в системі охолодження?", "yes_cell": "D12", "no_cell": "E12", "remark_cell": "F12"},
    {"text": "Braking system fully functional (incl. handbrake)?\nГальмівна система справна (в т.ч. ручне гальмо)?", "yes_cell": "D13", "no_cell": "E13", "remark_cell": "F13"},
    {"text": "Lighting system fully functional?\nСистема освітлення справна?", "yes_cell": "D14", "no_cell": "E14", "remark_cell": "F14"},
    {"text": "Enough tread and pressure in all tires?\nПротектор і тиск у всіх шинах достатні?", "yes_cell": "D15", "no_cell": "E15", "remark_cell": "F15"},
    {"text": "Tools for tire replacement present in the vehicle?\nІнструменти для заміни шин присутні в автомобілі?", "yes_cell": "D16", "no_cell": "E16", "remark_cell": "F16"},
    {"text": "First aid kit complete and present in the vehicle?\nАптечка повна і присутня в автомобілі?", "yes_cell": "D17", "no_cell": "E17", "remark_cell": "F17"},
    {"text": "Fire extinguisher functional and ready to use?\nВогнегасник справний та готовий до використання?", "yes_cell": "D19", "no_cell": "E19", "remark_cell": "F19"},
    {"text": "NPA stickers present and clearly visible?\nНаклейки NPA присутні та чіткі?", "yes_cell": "D20", "no_cell": "E20", "remark_cell": "F20"},
    {"text": "Are damages on body, windscreens, mirrors, lights absent?\nПошкоджень на кузові, лобовому склі, дзеркалах, фарах немає?", "yes_cell": "D21", "no_cell": "E21", "remark_cell": "F21"},
    {"text": "Are other damages or malfunctions compared to previous monthly check absent?\nІнші пошкодження або несправності порівняно з попередньою перевіркою відсутні?", "yes_cell": "D22", "no_cell": "E22", "remark_cell": "F22"},
]