MONTHLY_QUESTIONS = [
    {"text": "Registration, insurance documents and instruction present in the vehicle?\nРеєстраційні, страхові документи та інструкція присутні в транспортному засобі?", "yes_cell": "E8", "no_cell": "F8", "remark_cell": "G8"},
    {"text": "Keys opening all locks present?\nКлючі присутні в транспортному засобі та відкривають всі замки?", "yes_cell": "E9", "no_cell": "F9", "remark_cell": "G9"},
    {"text": "Engine oil changed as per schedule?\nМоторне масло змінене за графіком?", "yes_cell": "E10", "no_cell": "F10", "remark_cell": "G10"},
    {"text": "Enough oil in the engine?\nДостатня кількість масла в двигуні?", "yes_cell": "E11", "no_cell": "F11", "remark_cell": "G11"},
    {"text": "Enough power steering oil?\nДостатня кількість масла для гідропідсилювача керма?", "yes_cell": "E12", "no_cell": "F12", "remark_cell": "G12"},
    {"text": "Enough liquid in the cooling system?\nДостатньо рідини в системі охолодження?", "yes_cell": "E13", "no_cell": "F13", "remark_cell": "G13"},
    {"text": "Braking system fully functional (incl. handbrake)?\nГальмівна система справна (в т.ч. ручне гальмо)?", "yes_cell": "E14", "no_cell": "F14", "remark_cell": "G14"},
    {"text": "Lighting system fully functional?\nСистема освітлення справна?", "yes_cell": "E15", "no_cell": "F15", "remark_cell": "G15"},
    {"text": "Enough tread and pressure in all tires?\nПротектор і тиск у всіх шинах достатні?", "yes_cell": "E16", "no_cell": "F16", "remark_cell": "G16"},
    {"text": "Tools for tire replacement present in the vehicle?\nІнструменти для заміни шин присутні в автомобілі?", "yes_cell": "E17", "no_cell": "F17", "remark_cell": "G17"},
    {"text": "First aid kit complete and present in the vehicle?\nАптечка повна і присутня в автомобілі?", "yes_cell": "E18", "no_cell": "F18", "remark_cell": "G18"},
    {"text": "Fire extinguisher functional and ready to use?\nВогнегасник справний та готовий до використання?", "yes_cell": "E19", "no_cell": "F19", "remark_cell": "G19"},
    {"text": "NPA stickers present and clearly visible?\nНаклейки NPA присутні та чіткі?", "yes_cell": "E20", "no_cell": "F20", "remark_cell": "G20"},
    {"text": "Are damages on body, windscreens, mirrors, lights absent?\nПошкоджень на кузові, лобовому склі, дзеркалах, фарах немає?", "yes_cell": "E21", "no_cell": "F21", "remark_cell": "G21"},
    {"text": "Are other damages or malfunctions compared to previous monthly check absent?\nІнші пошкодження або несправності порівняно з попередньою перевіркою відсутні?", "yes_cell": "E22", "no_cell": "F22", "remark_cell": "G22"},
]
